dbt_test:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: 'dbt_test.duckdb'
      threads: 1
    databricks:
      type: databricks
      host: https://adb-3679152566148441.1.azuredatabricks.net
      http_path: "/sql/1.0/warehouses/874016300d69e784"
      token: "{{ env_var('DATABRICKS_AZURE_PAT') }}"
      catalog: "dbt_test"
      schema: "dbt_models"
      threads: 1
